feat: stats v.1
notebyte7/java-explore-with-me pull request #3
Opened 2023-07-01 15:56 UTC by notebyte7

2023-07-01 19:50 UTC, AnastasiyaFomkina requested changes

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-client/src/main/java/ru/practicum/StatsClient.java
> +    public void postEndpointHit(EndpointHitDto endpointHitDto) {
Лучше возвращать ответ с помощью `ResponseEntity`

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/controller/StatsServerController.java
> +    public Collection<ViewStatsDto> getViewStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
* Лучше возвращать не `Collection` менее абстрактный интерфейс - `List`, так мы точно будем знать какой тип коллекции ожидать в ответе
* Лучше сделать `pattern` в публичной константой и вынести его в отдельный класс, чтобы можно было  переиспользовать его, а не дублировать

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/exception/ErrorResponse.java
> +    public ErrorResponse(String error) {
Можно заменить на `@AllArgsConstructor` и `@Getter` от `lombok`

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/model/EndpointHit.java
> +    Long id;
Нет модификаторов доступа у полей класса

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/model/ViewStats.java
> +public class ViewStats {
Нет модификаторов доступа у полей класса

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/repository/StatsRepository.java
> +    Collection<ViewStats> getViewStatsUniqueIp(LocalDateTime start, LocalDateTime end, List<String> uris);
Нужно заменить на менее абстрактную коллекцию

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/repository/StatsRepository.java
> +    Collection<ViewStats> getViewStatsNotUniqueIp(LocalDateTime start, LocalDateTime end, List<String> uris);
Нужно заменить на менее абстрактную коллекцию

2023-07-01 19:50 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/service/StatsService.java
> +    Collection<ViewStatsDto> getViewStats(LocalDateTime start, LocalDateTime end, String[] uris, Boolean unique);
Нужно заменить на менее абстрактную коллекцию

2023-07-01 19:54 UTC, notebyte7 commented on stats-service/stats-service-server/src/main/java/ru/practicum/controller/StatsServerController.java
> +    public Collection<ViewStatsDto> getViewStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Очень странно получается, Борис всегда говорил что лучше Collection. И приучил меня к этому, а вот теперь уже другой ревьюер - и другие правила(

2023-07-01 19:56 UTC, AnastasiyaFomkina commented on stats-service/stats-service-server/src/main/java/ru/practicum/controller/StatsServerController.java
> +    public Collection<ViewStatsDto> getViewStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Видимо, каждый отталкивается от того, что принято у него в компании 😀
Можешь тогда не переделывать, а оставить так

2023-07-02 01:56 UTC, AnastasiyaFomkina approved these changes

2023-07-02 11:56 UTC, merged